//
// Created by phuc on 06/06/2021.
//

#ifndef FEATURE_EXTRACTION_EXTRACTBEZIERFEATURES_H
#define FEATURE_EXTRACTION_EXTRACTBEZIERFEATURES_H


class ExtractBezierFeatures {

};


#endif //FEATURE_EXTRACTION_EXTRACTBEZIERFEATURES_H
